export const techStacks = [
  { name: "javascript", category: ["frontend"], popular: true },
  { name: "typescript", category: ["frontend", "etc"], popular: true },
  { name: "react", category: ["frontend", "etc"], popular: true },
  { name: "vue", category: ["frontend", "etc"], popular: true },
  { name: "nodejs", category: ["backend", "etc"], popular: true },
  { name: "spring", category: ["backend", "etc"], popular: true },
  { name: "java", category: ["backend", "etc"], popular: true },
  { name: "nextjs", category: ["frontend", "etc"], popular: true },
  { name: "nestjs", category: ["backend", "etc"], popular: true },
  { name: "express", category: ["backend", "etc"], popular: false },
  { name: "go", category: ["backend", "etc"], popular: false },
  { name: "c", category: [], popular: false },
  { name: "python", category: ["backend", "etc"], popular: false },
  { name: "django", category: ["backend", "etc"], popular: false },
  { name: "swift", category: ["mobile", "etc"], popular: true },
  { name: "kotlin", category: ["backend", "mobile", "etc"], popular: true },
  { name: "mysql", category: ["backend", "etc"], popular: false },
  { name: "mongodb", category: ["backend", "etc"], popular: false },
  { name: "php", category: ["backend", "etc"], popular: false },
  { name: "graphql", category: ["backend", "etc"], popular: false },
  { name: "firebase", category: ["backend", "etc"], popular: false },
  { name: "reactnative", category: ["mobile", "etc"], popular: false },
  { name: "unity", category: ["mobile", "etc"], popular: false },
  { name: "flutter", category: ["mobile", "etc"], popular: true },
  { name: "aws", category: ["etc"], popular: false },
  { name: "kubernetes", category: ["etc"], popular: false },
  { name: "docker", category: ["etc"], popular: false },
  { name: "git", category: ["etc"], popular: false },
  { name: "figma", category: ["etc"], popular: true },
  { name: "zeplin", category: ["etc"], popular: false },
  { name: "jest", category: ["etc"], popular: false },
  { name: "svelte", category: ["frontend", "etc"], popular: false },
];
